# Generated by Django 5.0.4 on 2024-04-24 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_Id', models.CharField(max_length=155, verbose_name='Course ID')),
                ('course_name', models.CharField(max_length=255, verbose_name='Course Name')),
                ('course_description', models.TextField(verbose_name='Course Description')),
                ('course_total_registered', models.PositiveIntegerField(default=0, verbose_name='Total Students')),
                ('status', models.BooleanField(default=True)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Instructor')),
            ],
        ),
    ]
